<?php
/**
 * Implements hook_theme().
 */
function paragraphs_iframe_preview_theme() {
  return [
    'page__paragraph_iframe_preview' => ['base hook' => 'page'],
    'paragraph__preview' => ['base hook' => 'paragraph'],
  ];
}

/**
 * Implements hook_preprocess_html().
 *
 * Removes page chrome for paragraph iframe previews.
 */
function paragraphs_iframe_preview_preprocess_html(array &$variables) {
  if (\Drupal::routeMatch()->getRouteName() === 'paragraphs_iframe_preview.paragraph_iframe_preview') {
    unset($variables['page_top'], $variables['page_bottom'], $variables['attributes']);
  }
}

/**
 * Implements hook_preprocess_paragraph__preview().
 *
 * Stores the temporary paragraph entity in PrivateTempStoreFactory so it can be
 * retrieved later in the iframe preview context.
 *
 */
function paragraphs_iframe_preview_preprocess_paragraph__preview(array &$variables) {
  // Drupal already provides either:
  // - the temporary modified version if the paragraph is collapsed
  // - or the last saved version if returning to the node edit form
  $paragraph = $variables['elements']['#paragraph'];
  /** @var \Drupal\Core\TempStore\PrivateTempStoreFactory $tempstore_factory */
  $tempstore_factory = \Drupal::service('tempstore.private'); // stores inside key_value_expire table
  $paragraph_preview_store = $tempstore_factory->get('paragraph_preview'); // where collection = tempstore.private.paragraph_preview
  $paragraph_uuid = $paragraph->uuid();
  // Uses the paragraph UUID as the storage key (column name) since the paragraph may not yet have a database ID
  $paragraph_preview_store->set($paragraph_uuid, $paragraph);
  $variables['paragraph_uuid'] = $paragraph_uuid;
  $variables['paragraph_bundle'] = $paragraph->bundle();
}




